# Generated by Django 2.1.1 on 2018-10-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='user',
        ),
        migrations.AddField(
            model_name='picture',
            name='img',
            field=models.ImageField(blank=True, upload_to='pictures'),
        ),
        migrations.AddField(
            model_name='picture',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
