# Generated by Django 2.1.1 on 2018-10-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_picture_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='file',
            field=models.FileField(blank=True, upload_to='files'),
        ),
    ]
